version: '3.8'

services:
  actual-investment-sync:
    # Use the published GHCR image by default; comment out 'image' and uncomment 'build' to rebuild locally
    image: ghcr.io/rjlee/actual-investment-sync:latest
    # build: .
    container_name: actual-investment-sync
    env_file:
      - .env
    ports:
      - '${HTTP_PORT:-3000}:${HTTP_PORT:-3000}'
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./data/budget
        target: /app/budget
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
